set(_CATKIN_CURRENT_PACKAGE "robot_sec_nodes")
set(robot_sec_nodes_VERSION "0.0.0")
set(robot_sec_nodes_MAINTAINER "longyucheng <longyucheng@todo.todo>")
set(robot_sec_nodes_PACKAGE_FORMAT "2")
set(robot_sec_nodes_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_sec_nodes_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_sec_nodes_BUILDTOOL_DEPENDS "catkin")
set(robot_sec_nodes_BUILDTOOL_EXPORT_DEPENDS )
set(robot_sec_nodes_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_sec_nodes_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_sec_nodes_TEST_DEPENDS )
set(robot_sec_nodes_DOC_DEPENDS )
set(robot_sec_nodes_DEPRECATED "")