// Generated by gencpp from file ur_control/RG2.msg
// DO NOT EDIT!


#ifndef UR_CONTROL_MESSAGE_RG2_H
#define UR_CONTROL_MESSAGE_RG2_H

#include <ros/service_traits.h>


#include <ur_control/RG2Request.h>
#include <ur_control/RG2Response.h>


namespace ur_control
{

struct RG2
{

typedef RG2Request Request;
typedef RG2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RG2
} // namespace ur_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_control::RG2 > {
  static const char* value()
  {
    return "e9f43d43d0606566dbbf901fbd3b24a0";
  }

  static const char* value(const ::ur_control::RG2&) { return value(); }
};

template<>
struct DataType< ::ur_control::RG2 > {
  static const char* value()
  {
    return "ur_control/RG2";
  }

  static const char* value(const ::ur_control::RG2&) { return value(); }
};


// service_traits::MD5Sum< ::ur_control::RG2Request> should match 
// service_traits::MD5Sum< ::ur_control::RG2 > 
template<>
struct MD5Sum< ::ur_control::RG2Request>
{
  static const char* value()
  {
    return MD5Sum< ::ur_control::RG2 >::value();
  }
  static const char* value(const ::ur_control::RG2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_control::RG2Request> should match 
// service_traits::DataType< ::ur_control::RG2 > 
template<>
struct DataType< ::ur_control::RG2Request>
{
  static const char* value()
  {
    return DataType< ::ur_control::RG2 >::value();
  }
  static const char* value(const ::ur_control::RG2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_control::RG2Response> should match 
// service_traits::MD5Sum< ::ur_control::RG2 > 
template<>
struct MD5Sum< ::ur_control::RG2Response>
{
  static const char* value()
  {
    return MD5Sum< ::ur_control::RG2 >::value();
  }
  static const char* value(const ::ur_control::RG2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_control::RG2Response> should match 
// service_traits::DataType< ::ur_control::RG2 > 
template<>
struct DataType< ::ur_control::RG2Response>
{
  static const char* value()
  {
    return DataType< ::ur_control::RG2 >::value();
  }
  static const char* value(const ::ur_control::RG2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_CONTROL_MESSAGE_RG2_H
