// Generated by gencpp from file ur_control/RG2_GripResponse.msg
// DO NOT EDIT!


#ifndef UR_CONTROL_MESSAGE_RG2_GRIPRESPONSE_H
#define UR_CONTROL_MESSAGE_RG2_GRIPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_control
{
template <class ContainerAllocator>
struct RG2_GripResponse_
{
  typedef RG2_GripResponse_<ContainerAllocator> Type;

  RG2_GripResponse_()
    : gripped(false)  {
    }
  RG2_GripResponse_(const ContainerAllocator& _alloc)
    : gripped(false)  {
  (void)_alloc;
    }



   typedef uint8_t _gripped_type;
  _gripped_type gripped;




  typedef boost::shared_ptr< ::ur_control::RG2_GripResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_control::RG2_GripResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RG2_GripResponse_

typedef ::ur_control::RG2_GripResponse_<std::allocator<void> > RG2_GripResponse;

typedef boost::shared_ptr< ::ur_control::RG2_GripResponse > RG2_GripResponsePtr;
typedef boost::shared_ptr< ::ur_control::RG2_GripResponse const> RG2_GripResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_control::RG2_GripResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_control::RG2_GripResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_control::RG2_GripResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_control::RG2_GripResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_control::RG2_GripResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e59cc69aa535dfedb8f29528fe2a1de3";
  }

  static const char* value(const ::ur_control::RG2_GripResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe59cc69aa535dfedULL;
  static const uint64_t static_value2 = 0xb8f29528fe2a1de3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_control/RG2_GripResponse";
  }

  static const char* value(const ::ur_control::RG2_GripResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool gripped\n\
\n\
";
  }

  static const char* value(const ::ur_control::RG2_GripResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RG2_GripResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_control::RG2_GripResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_control::RG2_GripResponse_<ContainerAllocator>& v)
  {
    s << indent << "gripped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_CONTROL_MESSAGE_RG2_GRIPRESPONSE_H
