set(_CATKIN_CURRENT_PACKAGE "ur_control")
set(ur_control_VERSION "0.0.0")
set(ur_control_MAINTAINER "ilab <ilab@todo.todo>")
set(ur_control_PACKAGE_FORMAT "1")
set(ur_control_BUILD_DEPENDS "roscpp" "std_msgs" "roslib" "std_msgs" "geometry_msgs" "eigen_conversions" "visualization_msgs" "message_generation" "actionlib" "control_msgs" "moveit_ros_move_group" "moveit_ros_planning_interface")
set(ur_control_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_ros_planning_interface" "actionlib" "control_msgs" "roscpp" "roslib" "std_msgs" "geometry_msgs" "eigen_conversions" "visualization_msgs" "message_runtime")
set(ur_control_BUILDTOOL_DEPENDS "catkin")
set(ur_control_BUILDTOOL_EXPORT_DEPENDS )
set(ur_control_EXEC_DEPENDS "moveit_ros_move_group" "moveit_ros_planning_interface" "actionlib" "control_msgs" "roscpp" "roslib" "std_msgs" "geometry_msgs" "eigen_conversions" "visualization_msgs" "message_runtime")
set(ur_control_RUN_DEPENDS "moveit_ros_move_group" "moveit_ros_planning_interface" "actionlib" "control_msgs" "roscpp" "roslib" "std_msgs" "geometry_msgs" "eigen_conversions" "visualization_msgs" "message_runtime")
set(ur_control_TEST_DEPENDS )
set(ur_control_DOC_DEPENDS )
set(ur_control_DEPRECATED "")